config/routes.rb
Myapp::Application.routes.draw do
 

  post "/api/v1/user/register" => "api_users#register"
  post "/api/v1/user/auth" => "api_users#authenticate"

  resources :projects, param: :uuid, path: "/api/v1/user/projects", controller: :api_user_projects, except: [ :edit, :new ], as: :api_v1_user_projects

  get "/api/v1/projects" => "api_projects#index"
  get "/api/v1/projects/:uuid" => "api_projects#show"
  get "/api/v1/projects/:uuid/download" => "api_projects#download"
  get "/api/v1/projects/:uuid/fork" => "api_projects#fork"

  resources :shared_projects, path: "/api/v1/shared_projects", controller: :api_shared_projects, only: [ :create ]
  
  
  resources :shared_projects, only: [ :show ]
  resources :projects, only: [ :show ]

  root 'shared_projects#index'

  get "/browse" => "page#browse", as: :browse_projects
  get "/tutorial" => "page#tutorial", as: :tutorial

end

app/views/page/browse.html.erb
<div class="container purple">
  <div id="browse-container">
    <div class="filter-controls">
      
      <form method="get">
        <label id="browse-by-label">Browse by:</label>
        <select name="category" onchange="this.form.submit()">
          <option value="popular" <%= "selected=\"selected\"" if params[:category] == "popular"%>>Most Popular</option>
          <option value="newest" <%= "selected=\"selected\"" if params[:category] == "newest"%>>Newest</option>
        </select>
      </form>

      <%= paginate @projects %>
    </div>
    <div id="results">
      <div class="row">
      <% count = 1 %>
      <% @projects.each do |project| %>
        <div class="game">
          <a href="<%= project_path(project) %>"><img class="screenshot" alt="<%= project.title %>" src="<%= project.screenshot.url(:half) %>" /></a>
          <a class="text-link" href="<%= project_path(project) %>"><%= project.title %></a>
          <p><b>Username:</b> <%= project.user.username %></p>
          <p><b>Views:</b> <%= project.views %></p>
          <p><b>Created:</b> <%= project.created_at %></p>
        </div>

        <% if ((count % 5) == 0 && count < params[:per_page].to_i) %>
          </div>
          <div class="row">
        <% end %>
        <% count = count + 1 %>
      <% end %>
      </div>
      <div class="filter-controls-bottom">
       <%= paginate @projects %>
      </div>
    </div>
  </div>
</div>

app/views/page/tutorial.html.erb
<div class="container green">
  <div id="tutorial-container">
    <h1 id="title">Tutorial</h1>
    <p>The video below shows examples of how to use our iOS app Zuse.</p>

    <iframe width="600" height="450" src="//www.youtube.com/embed/bpW8ipEpjZ8" frameborder="0" allowfullscreen></iframe> 
  </div>
</div>