config/routes.rb
Myapp::Application.routes.draw do
 

  post "/api/v1/user/register" => "api_users#register"
  post "/api/v1/user/auth" => "api_users#authenticate"

  resources :projects, param: :uuid, path: "/api/v1/user/projects", controller: :api_user_projects, except: [ :edit, :new ], as: :api_v1_user_projects

  get "/api/v1/projects" => "api_projects#index"
  get "/api/v1/projects/:uuid" => "api_projects#show"
  get "/api/v1/projects/:uuid/download" => "api_projects#download"
  get "/api/v1/projects/:uuid/fork" => "api_projects#fork"

  resources :shared_projects, path: "/api/v1/shared_projects", controller: :api_shared_projects, only: [ :create ]
  
  
  resources :shared_projects, only: [ :show ]
  resources :projects, only: [ :show ]

  root 'shared_projects#index'

  get "/browse" => "page#browse", as: :browse_projects
  get "/tutorial" => "page#tutorial", as: :tutorial

end

app/models/shared_project.rb
class SharedProject < ActiveRecord::Base
 
  validates :project_json, :compiled_components, presence: true
  validate :project_json_is_valid
  validate :compiled_components_is_valid

  def project_json_is_valid
    if !self.project_json.blank?
      begin
        JSON.parse self.project_json
      rescue JSON::ParserError
        errors.add(:project_json, "is not valid JSON")
      end
    end
  end

  def compiled_components_is_valid
    if !self.compiled_components.blank?
      begin
        JSON.parse self.compiled_components
      rescue JSON::ParserError
        errors.add(:compiled_components, "is not valid JSON")
      end
    end
  end
end

app/controllers/shared_projects_controller.rb
class SharedProjectsController < ApplicationController
  layout "shared_projects"
  

  def show
    @shared_project = SharedProject.find_by_id params[:id]
    project_json = JSON.parse @shared_project.project_json
    @title = project_json["title"]
    @description = project_json["description"]

    if @shared_project.nil?
      redirect_to "/404.html", status: :not_found
    end
  end

  def index
    @title = "Home"
    @shared_project = SharedProject.find_by_id 34
  end
end

app/helpers/shared_projects_helper.rb
module SharedProjectsHelper
end

app/views/shared_projects/create.html.erb
<h1>SharedProjects#create</h1>
<p>Find me in app/views/shared_projects/create.html.erb</p>

app/views/shared_projects/index.html.erb
<div class="container blue">
  <div id="root-container">
    <div id="project-meta">
      <h1 id="title">What is Zuse?</h1>
      
      <div id="description">
        <p>
          Zuse is a delightful, fun to use iOS app that teaches you how to program through making games.
        </p>
        <p>
          While the first projects you make will likely be on par with Pong or Breakout, before you know it
          you will be able to program more complex games like Galaga here on the right.
        </p>
        <p>
          And Zuse allows you to share the games you make with your friends through ZuseHub, Facebook, and Twitter.
        </p>
        <p>
          We can't wait to see what you come up with!
        </p>
      </div>
    </div>

    <div id="canvas-container">
      <canvas id="viewport"></canvas>
      <div id="canvas-controls">
        <div id="play-panel">
          <span id="refresh" title="start" class="icon ion-refresh"></span>
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/shared_projects/show.html.erb
<div class="container green">
  <div id="shared-project-container">
    <div id="project-meta">
      <h1 id="title"><%= @title %></h1>
      
      <p id="description">
        This project's description, detailing its functionality, would go here if this project had a description detailing its functionality.
      </p>

      <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= shared_project_url(@shared_project) %>" data-text="Just played <%= @title %>">Tweet</a>
      <div class="fb-share-button" data-href="<%= shared_project_url(@shared_project) %>" data-type="button_count" style="top: -5px; margin-left: -20px;"></div>
    </div>

    <div id="canvas-container">
      <canvas id="viewport"></canvas>
      <div id="canvas-controls">
        <div id="play-panel">
          <span id="refresh" title="start" class="icon ion-refresh"></span>
        </div>
      </div>
    </div>
    
  </div>
</div>