config/routes.rb
Myapp::Application.routes.draw do
 

  post "/api/v1/user/register" => "api_users#register"
  post "/api/v1/user/auth" => "api_users#authenticate"

  resources :projects, param: :uuid, path: "/api/v1/user/projects", controller: :api_user_projects, except: [ :edit, :new ], as: :api_v1_user_projects

  get "/api/v1/projects" => "api_projects#index"
  get "/api/v1/projects/:uuid" => "api_projects#show"
  get "/api/v1/projects/:uuid/download" => "api_projects#download"
  get "/api/v1/projects/:uuid/fork" => "api_projects#fork"

  resources :shared_projects, path: "/api/v1/shared_projects", controller: :api_shared_projects, only: [ :create ]
  
  
  resources :shared_projects, only: [ :show ]
  resources :projects, only: [ :show ]

  root 'shared_projects#index'

  get "/browse" => "page#browse", as: :browse_projects
  get "/tutorial" => "page#tutorial", as: :tutorial

end

app/views/layouts/_footer.html.erb
<div id="footer">
&copy; 2014 ZuseHub Senior Capstone Project Group
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <a href="<%= root_path %>"><img id="logo" src="/images/logo.png" /></a>

  <ul id="navigation">
    <a href="<%= root_path %>"><li>Home</li></a>
    <a href="<%= tutorial_path %>"><li>Tutorial</li></a>
    <a href="<%= browse_projects_path %>"><li>Browse</li></a>
  </ul>
</div>

app/views/layouts/_social_media.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=1426724497578315";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZuseHub</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zuse Hub - Browse</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,800,700,600,300' rel='stylesheet' type='text/css' />
  <link rel='stylesheet' type='text/css' href="http://code.ionicframework.com/ionicons/1.4.1/css/ionicons.min.css"/>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render "layouts/header" %>

  <%= yield %>

  <%= render "layouts/footer" %>
</body>
</html>

app/views/layouts/projects.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zuse Hub - <%= @project.title %></title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,800,700,600,300' rel='stylesheet' type='text/css' />
  <link rel='stylesheet' type='text/css' href="http://code.ionicframework.com/ionicons/1.4.1/css/ionicons.min.css"/>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_tag do %>
    $(function () {
      window.project_json = <%= raw @commit.project_json %>;

      window.compiled_components = <%= raw @commit.compiled_components %>;

      window.game = new ZuseAppEngine( { canvas: $("#viewport"), project_json: window.project_json, compiled_components: window.compiled_components } );
    });
  <% end %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render "layouts/social_media" %>
  <%= render "layouts/header" %>

  <%= yield %>

  <%= render "layouts/footer" %>
</body>
</html>

app/views/layouts/shared_projects.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zuse Hub - <%= @title %></title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,800,700,600,300' rel='stylesheet' type='text/css' />
  <link rel='stylesheet' type='text/css' href="http://code.ionicframework.com/ionicons/1.4.1/css/ionicons.min.css"/>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_tag do %>
    $(function () {
      window.project_json = <%= raw @shared_project.project_json %>;

      window.compiled_components = <%= raw @shared_project.compiled_components %>;

      window.game = new ZuseAppEngine( { canvas: $("#viewport"), project_json: window.project_json, compiled_components: window.compiled_components } );
    });
  <% end %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=1426724497578315";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>

  <%= render "layouts/header" %>

<%= yield %>

</body>
</html>